# Generated by Django 2.1.15 on 2020-02-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('identidad', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('p_nombre', models.CharField(max_length=20)),
                ('s_nombre', models.CharField(max_length=20)),
                ('p_apellido', models.CharField(max_length=20)),
                ('s_apellido', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_registro', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
