# Generated by Django 2.1.15 on 2020-03-05 18:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EncabezadoFactura',
            fields=[
                ('factura', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('Fecha_proceso', models.DateField(auto_now_add=True)),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HabitacionesOcupadas',
            fields=[
                ('registro', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('no_habitacion', models.CharField(max_length=5)),
                ('fecha_registro', models.DateField()),
                ('fecha_retiro', models.DateField()),
                ('Habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.Habitacion')),
            ],
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.EncabezadoFactura'),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='habitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.HabitacionesOcupadas'),
        ),
    ]
